//! Wine debug data extracted from Wine source code
//! 
//! This file is auto-generated by the wine-extract tool.
//! Do not edit manually - regenerate with:
//!   wine-extract --wine-path /path/to/wine --output src/wine_data.rs protontool
//!
//! Source: Valve's Wine/Proton fork

/// All Wine debug channels extracted from Wine source
/// Use with WINEDEBUG=+channel to enable tracing
pub const WINE_DEBUG_CHANNELS: &[&str] = &[
    "acledit", "aclui", "actctx", "activeds", "actxprxy", "adpcm", "adsldp", "advapi",
    "advpack", "alsa", "amd_ags", "amdxc", "amsi", "android", "animate", "appbar",
    "apphelp", "appwizcpl", "appx", "asmshader", "aspi", "atiadlxx", "atl", "atlthunk",
    "atmlib", "atom", "authz", "avicap", "avifile", "avrt", "bcrypt", "bidi",
    "bitblt", "bitmap", "bluetooth", "bluetoothapis", "browseui", "button", "bytecodewriter", "cabinet",
    "capi", "capture", "cards", "cdosys", "cdrom", "class", "clipboard", "clipping",
    "clusapi", "combase", "combo", "comboex", "comm", "commctrl", "commdlg", "compstui",
    "comsvcs", "concrt", "connect", "connectivity", "console", "context", "coreaudio", "cred",
    "credentials", "credui", "crypt", "cryptasn", "cryptdlg", "cryptext", "cryptnet", "crypto",
    "cryptui", "ctapi32", "cursor", "d2d", "d3d", "d3d10", "d3d10core", "d3d11",
    "d3d12", "d3d8", "d3d9", "d3d_decl", "d3d_shader", "d3dcompiler", "d3drm", "d3dx",
    "d3dxof", "d3dxof_parsing", "data", "dataexchange", "datetime", "davclnt", "dbgeng", "dbghelp",
    "dbghelp_coff", "dbghelp_dwarf", "dbghelp_macho", "dbghelp_msc", "dbghelp_pdb", "dbghelp_stabs", "dc", "dciman",
    "dcomp", "ddeml", "ddraw", "ddrawex", "debug_buffer", "debugstr", "deskcpl", "devenum",
    "dhcpcsvc", "dhtmled", "dialog", "diasymreader", "dib", "difxapi", "dinput", "display",
    "dll", "dmband", "dmcompos", "dmfile", "dmime", "dmloader", "dmo", "dmobj",
    "dmscript", "dmstyle", "dmsynth", "dmusic", "dmusic32", "dnsapi", "dosmem", "dpa",
    "dplay", "dpnet", "dpnhpast", "dpnhupnp", "dpvoice", "driver", "dsa", "dsdmo",
    "dsound", "dsound3d", "dsquery", "dssenh", "dsuiext", "dswave", "dwmapi", "dwrite",
    "dx8vb", "dxcore", "dxdiag", "dxgi", "dxtrans", "dxva2", "edit", "enhmetafile",
    "enumeration", "environ", "esync", "event", "eventlog", "evr", "exec", "explorerframe",
    "faultrep", "file", "fixup", "fltlib", "fltmgr", "font", "fontcache", "fontsub",
    "fsync", "fusion", "fwpuclnt", "g711", "gamebar", "gameux", "gamingtcui", "gdi",
    "gdiplus", "geolocator", "gl_compat", "global", "globalmem", "glu", "graphics", "gsm",
    "handle", "header", "heap", "hid", "hlink", "hnetcfg", "hook", "hostname",
    "hotkey", "htmlhelp", "http", "hvsi", "iccvid", "icm", "icmui", "icon",
    "ieframe", "iertutil", "image", "imagehlp", "imagelist", "imm", "inetcomm", "inetcpl",
    "inetmib1", "infosoft", "inkobj", "input", "inseng", "int", "int21", "int31",
    "ipaddress", "iphlpapi", "ir50_32", "itss", "joycpl", "jscript", "jsproxy", "kerberos",
    "kernelbase", "keyboard", "ksecdd", "lanman", "listbox", "listview", "loadperf", "local",
    "locale", "localspl", "localui", "macdrv", "manipulation", "mapi", "mci", "mciavi",
    "mcicda", "mcimidi", "mciqtz", "mciwave", "mdi", "media", "mediacontrol", "menu",
    "message", "messaging", "metafile", "mfplat", "mgmtapi", "midi", "mlang", "mmaux",
    "mmc", "mmdevapi", "mmio", "mmsys", "mmtime", "model", "module", "monthcal",
    "mountmgr", "mp3dmod", "mpeg3", "mpr", "mprapi", "msacm", "msado15", "msasn1",
    "mscms", "mscoree", "msctf", "msctfmonitor", "msdasql", "msdmo", "msdrm", "msftedit",
    "msg", "mshtml", "msi", "msidb", "msident", "msimg32", "msimtf", "msisip",
    "msisys", "msnet", "msopc", "mspatcha", "msrle32", "msscript", "mssign", "mstask",
    "msttsengine", "msvcirt", "msvcm", "msvcp", "msvcrt", "msvidc32", "msvideo", "mswsock",
    "msxml", "nativefont", "ncrypt", "nddeapi", "ndis", "netapi32", "netbios", "netcfgx",
    "netio", "netprofm", "netutils", "ninput", "nls", "nsi", "nstc", "ntdll",
    "ntdsapi", "ntlm", "ntoskrnl", "ntprint", "objsel", "odbc", "ole", "oleacc",
    "oledb", "oledlg", "olemalloc", "olepicture", "onlineid", "opencl", "opengl", "oss",
    "packager", "pager", "palette", "path", "pdh", "perception", "pidgen", "pidl",
    "plugplay", "powermgnt", "powrprof", "print", "printui", "prntvpt", "process", "profile",
    "progress", "propsheet", "propsys", "protontts", "psdrv", "pstores", "pulse", "qmgr",
    "quartz", "query", "qwave", "ras", "rasdlg", "rawinput", "rebar", "recyclebin",
    "reg", "region", "relay", "resource", "richedit", "richedit_lists", "rometadata", "rpc",
    "rstrtmgr", "rtutils", "sapi", "schannel", "schedsvc", "scrobj", "scroll", "scrrun",
    "scsiport", "secur32", "security", "seh", "selector", "sensapi", "server", "service",
    "setupapi", "sfc", "sharedgpures", "shcore", "shdocvw", "shell", "shlctrl", "slc",
    "smbios", "snmpapi", "snoop", "sound", "speech", "spoolss", "sspicli", "static",
    "statusbar", "sti", "storage", "stress", "string", "sxs", "sync", "syslevel",
    "syslink", "system", "systray", "t2embed", "tab", "tape", "tapi", "task",
    "taskdialog", "taskschd", "tbs", "tdh", "tdi", "text", "theme_scroll", "thread",
    "threadpool", "thunk", "toolbar", "toolhelp", "tooltips", "trackbar", "traffic", "treeview",
    "twain", "twinapi", "ui", "uianimation", "uiautomation", "uiribbon", "uniscribe", "unwind",
    "updown", "updspapi", "url", "urlmon", "usb", "usbd", "user", "userenv",
    "uxtheme", "variant", "vbscript", "vcomp", "vcruntime", "vdmdbg", "ver", "virtdisk",
    "virtual", "volume", "vssapi", "vulkan", "vxd", "wavemap", "waylanddrv", "wbemdisp",
    "wbemprox", "web", "webservices", "websocket", "wer", "wevtapi", "wgl", "wia",
    "wimgapi", "win", "wincodecs", "winebth", "winemapi", "wineusb", "wing", "winhttp",
    "wininet", "winmm", "winprint", "winscard", "winsock", "winspool", "winsta", "winstation",
    "winstring", "wintab", "wintab32", "wintrust", "wintypes", "winusb", "wlanapi", "wldap32",
    "wldp", "wmadec", "wmi", "wmiutils", "wmp", "wmvcore", "wnet", "wofutil",
    "wow", "wpc", "wpcap", "wsdapi", "wshom", "wsnmp32", "wtsapi", "wuapi",
    "x11drv", "xaudio2", "xim", "xinput", "xmlhttp", "xmllite", "xolehlp", "xrandr",
    "xrender", "xtajit", "xvidmode",
];

/// Database of known Wine/Windows errors and warnings
/// Format: (pattern to match, error code, description)
pub const KNOWN_ERRORS: &[(&str, &str, &str)] = &[
    // Wine crash/exception codes (from SEH - Structured Exception Handling)
    ("c0000005", "WINE-SEH-AV", "Access violation (STATUS_ACCESS_VIOLATION) - null pointer or bad memory access"),
    ("c0000006", "WINE-SEH-IPF", "In-page I/O error - disk or memory issue"),
    ("c0000008", "WINE-SEH-HANDLE", "Invalid handle - resource already closed or corrupted"),
    ("c000000d", "WINE-SEH-PARAM", "Invalid parameter passed to function"),
    ("c0000017", "WINE-SEH-NOMEM", "No memory available for operation"),
    ("c000001d", "WINE-SEH-ILLEGAL", "Illegal instruction - CPU incompatibility or corruption"),
    ("c0000025", "WINE-SEH-NONCON", "Noncontinuable exception - fatal error"),
    ("c0000026", "WINE-SEH-INVDISP", "Invalid disposition from exception handler"),
    ("c00000fd", "WINE-SEH-STACK", "Stack overflow - infinite recursion or large allocation"),
    ("c0000135", "WINE-SEH-NODLL", "DLL not found - missing dependency"),
    ("c0000138", "WINE-SEH-ORDINAL", "Ordinal not found in DLL - wrong DLL version"),
    ("c0000139", "WINE-SEH-ENTRYPT", "Entry point not found in DLL - API mismatch"),
    ("c0000142", "WINE-SEH-DLLINIT", "DLL initialization failed - check DLL dependencies"),
    ("c0000409", "WINE-SEH-STACKBUF", "Stack buffer overrun detected - security violation"),
    
    // Wine module/loader errors
    ("err:module:import_dll", "WINE-MODULE-001", "Failed to import DLL - check if DLL exists and dependencies are met"),
    ("err:module:load_dll", "WINE-MODULE-002", "Failed to load DLL - file missing, corrupted, or architecture mismatch"),
    ("err:module:attach_dlls", "WINE-MODULE-003", "DLL attach failed during process init"),
    ("err:module:LdrInitializeThunk", "WINE-MODULE-004", "Process initialization failed - critical DLL issue"),
    
    // Wine virtual memory errors
    ("err:virtual:map_file_into_view", "WINE-VIRT-001", "Memory mapping failed - insufficient memory or address space"),
    ("err:virtual:virtual_map_section", "WINE-VIRT-002", "Section mapping failed - memory layout issue"),
    ("err:virtual:allocate_virtual_memory", "WINE-VIRT-003", "Virtual memory allocation failed"),
    
    // Wine ntdll errors
    ("err:ntdll:RtlpWaitForCriticalSection", "WINE-NTDLL-001", "Critical section timeout - possible deadlock"),
    ("err:ntdll:NtTerminateProcess", "WINE-NTDLL-002", "Process termination error"),
    ("fixme:ntdll:NtQuerySystemInformation", "WINE-NTDLL-003", "Unimplemented system info query - usually harmless"),
    ("fixme:ntdll:EtwEventRegister", "WINE-NTDLL-004", "Event tracing not implemented - harmless"),
    
    // Wine display/window errors
    ("err:winediag:nodrv_CreateWindow", "WINE-DISPLAY-001", "No display driver - set DISPLAY env var or check X11/Wayland"),
    ("err:x11drv", "WINE-DISPLAY-002", "X11 driver error - check X server connection"),
    ("err:waylanddrv", "WINE-DISPLAY-003", "Wayland driver error - check Wayland compositor"),
    ("fixme:win:EnumDisplayDevices", "WINE-DISPLAY-004", "Display enumeration incomplete - cosmetic issue"),
    
    // Wine Direct3D/graphics errors
    ("fixme:d3d:", "WINE-D3D-001", "Direct3D feature not implemented - may cause graphical glitches"),
    ("err:d3d:", "WINE-D3D-002", "Direct3D error - graphics issue"),
    ("fixme:d3d11:", "WINE-D3D11-001", "Direct3D 11 feature incomplete"),
    ("fixme:d3d12:", "WINE-D3D12-001", "Direct3D 12 feature incomplete - consider using VKD3D"),
    ("fixme:dxgi:", "WINE-DXGI-001", "DXGI feature incomplete"),
    ("fixme:wined3d:", "WINE-WINED3D-001", "WineD3D implementation incomplete"),
    
    // Wine font/text errors
    ("fixme:dwrite:", "WINE-DWRITE-001", "DirectWrite incomplete - may affect text rendering"),
    ("fixme:font:", "WINE-FONT-001", "Font handling incomplete"),
    ("err:font:", "WINE-FONT-002", "Font error - check font installation"),
    
    // Wine input errors
    ("fixme:dinput:", "WINE-INPUT-001", "DirectInput incomplete - may affect game controllers"),
    ("err:dinput:", "WINE-INPUT-002", "DirectInput error"),
    ("fixme:xinput:", "WINE-XINPUT-001", "XInput incomplete - Xbox controller support"),
    
    // Wine audio errors
    ("err:alsa:", "WINE-AUDIO-001", "ALSA error - check ALSA configuration"),
    ("err:pulse:", "WINE-AUDIO-002", "PulseAudio error - check PulseAudio is running"),
    ("err:mmdevapi:", "WINE-AUDIO-003", "Audio device API error"),
    ("fixme:mmdevapi:", "WINE-AUDIO-004", "Audio API incomplete"),
    ("err:winmm:", "WINE-AUDIO-005", "Windows multimedia error"),
    ("fixme:dsound:", "WINE-AUDIO-006", "DirectSound incomplete"),
    
    // Wine network errors
    ("err:wininet:", "WINE-NET-001", "WinInet error - network/HTTP issue"),
    ("err:winhttp:", "WINE-NET-002", "WinHTTP error - HTTPS/HTTP issue"),
    ("err:winsock:", "WINE-NET-003", "Winsock error - socket/network issue"),
    ("fixme:winsock:", "WINE-NET-004", "Winsock feature incomplete"),
    ("fixme:iphlpapi:", "WINE-NET-005", "IP Helper API incomplete"),
    
    // Wine security/crypto errors
    ("err:crypt:", "WINE-CRYPT-001", "Cryptography error"),
    ("fixme:crypt:", "WINE-CRYPT-002", "Crypto feature incomplete"),
    ("fixme:bcrypt:", "WINE-BCRYPT-001", "BCrypt incomplete - may affect secure operations"),
    ("err:secur32:", "WINE-SEC-001", "Security API error"),
    
    // Wine shell/explorer errors
    ("fixme:shell:", "WINE-SHELL-001", "Shell feature incomplete"),
    ("fixme:explorer:", "WINE-EXPLORER-001", "Explorer feature incomplete"),
    
    // Wine OLE/COM errors
    ("fixme:ole:", "WINE-OLE-001", "OLE/COM feature incomplete"),
    ("err:ole:", "WINE-OLE-002", "OLE/COM error"),
    ("fixme:oleaut:", "WINE-OLEAUT-001", "OLE Automation incomplete"),
    
    // DXVK/VKD3D errors
    ("dxvk: Failed", "DXVK-001", "DXVK translation error - check Vulkan drivers"),
    ("dxvk: Unhandled", "DXVK-002", "DXVK unhandled case"),
    ("vkd3d: Failed", "VKD3D-001", "VKD3D-Proton error - DX12 to Vulkan translation"),
    ("vkd3d-proton: Failed", "VKD3D-002", "VKD3D-Proton error"),
    ("Vulkan: Failed", "VULKAN-001", "Vulkan initialization or operation failed"),
    ("VK_ERROR_", "VULKAN-002", "Vulkan error - check GPU drivers"),
    
    // Windows HRESULT error codes
    ("0x80004001", "HRESULT-E_NOTIMPL", "Not implemented"),
    ("0x80004002", "HRESULT-E_NOINTERFACE", "Interface not supported"),
    ("0x80004003", "HRESULT-E_POINTER", "Invalid pointer"),
    ("0x80004004", "HRESULT-E_ABORT", "Operation aborted"),
    ("0x80004005", "HRESULT-E_FAIL", "Unspecified failure"),
    ("0x80070002", "HRESULT-FILE_NOT_FOUND", "File not found"),
    ("0x80070003", "HRESULT-PATH_NOT_FOUND", "Path not found"),
    ("0x80070005", "HRESULT-E_ACCESSDENIED", "Access denied - check permissions"),
    ("0x8007000e", "HRESULT-E_OUTOFMEMORY", "Out of memory"),
    ("0x80070020", "HRESULT-SHARING_VIOLATION", "File in use by another process"),
    ("0x80070057", "HRESULT-E_INVALIDARG", "Invalid argument"),
    ("0x80070070", "HRESULT-DISK_FULL", "Disk full"),
    ("0x800700aa", "HRESULT-BUSY", "Resource busy"),
    ("0x800706ba", "HRESULT-RPC_UNAVAIL", "RPC server unavailable"),
    ("0x800706be", "HRESULT-RPC_FAILED", "RPC call failed"),
    ("0x80131500", "HRESULT-COR_E_EXCEPTION", ".NET exception"),
    ("0x80131509", "HRESULT-COR_E_INVALIDPROGRAM", "Invalid .NET program"),
    
    // NTSTATUS codes (0xC prefix)
    ("0xc0000005", "NTSTATUS-ACCESS_VIOLATION", "Access violation - memory error"),
    ("0xc000007b", "NTSTATUS-INVALID_IMAGE", "Invalid image format - 32/64-bit mismatch or corruption"),
    ("0xc0000135", "NTSTATUS-DLL_NOT_FOUND", "DLL not found - install required runtime"),
    ("0xc0000139", "NTSTATUS-ENTRYPOINT_NOT_FOUND", "Entry point not found in DLL"),
    ("0xc0000142", "NTSTATUS-DLL_INIT_FAILED", "DLL initialization failed"),
    ("0xc0000409", "NTSTATUS-STACK_BUFFER_OVERRUN", "Stack buffer overrun detected"),
    
    // .NET/CLR errors
    ("CLR error", "DOTNET-CLR-001", "CLR initialization error - install .NET runtime"),
    ("mscorlib", "DOTNET-MSCORLIB", ".NET core library issue"),
    ("System.IO.FileNotFoundException", "DOTNET-FILENOTFOUND", ".NET assembly or file not found"),
    ("System.DllNotFoundException", "DOTNET-DLLNOTFOUND", ".NET P/Invoke DLL not found"),
    ("System.BadImageFormatException", "DOTNET-BADIMAGE", ".NET assembly format error - architecture mismatch"),
    ("System.TypeLoadException", "DOTNET-TYPELOAD", ".NET type loading failed"),
    
    // DirectX errors
    ("D3DERR_INVALIDCALL", "DX-INVALIDCALL", "Invalid Direct3D call"),
    ("DXGI_ERROR_DEVICE_REMOVED", "DX-DEVICE_REMOVED", "GPU device removed - driver crash"),
    ("DXGI_ERROR_DEVICE_RESET", "DX-DEVICE_RESET", "GPU device reset"),
    ("DXGI_ERROR_DRIVER_INTERNAL_ERROR", "DX-DRIVER_ERROR", "GPU driver internal error"),
    ("DXGI_ERROR_NOT_FOUND", "DX-NOT_FOUND", "DXGI resource not found"),
    
    // Generic patterns
    ("Unhandled exception", "CRASH-EXCEPTION", "Unhandled exception - application crashed"),
    ("Segmentation fault", "CRASH-SEGFAULT", "Segmentation fault - memory access error"),
    ("page fault", "CRASH-PAGEFAULT", "Page fault - invalid memory access"),
    ("Assertion failed", "CRASH-ASSERT", "Assertion failure - programming error or corruption"),
    ("Stack overflow", "CRASH-STACKOVERFLOW", "Stack overflow - infinite recursion or deep call stack"),
    ("fatal error", "CRASH-FATAL", "Fatal error occurred"),
    ("cannot find", "ERROR-NOTFOUND", "Required file or resource not found"),
    ("permission denied", "ERROR-PERMISSION", "Permission denied - check file/folder permissions"),
    ("connection refused", "NET-REFUSED", "Network connection refused"),
    ("connection timed out", "NET-TIMEOUT", "Network connection timed out"),
    ("certificate", "NET-CERT", "SSL/TLS certificate issue"),
];

/// Check if a string is a valid Wine debug channel
pub fn is_valid_channel(channel: &str) -> bool {
    WINE_DEBUG_CHANNELS.contains(&channel)
}

/// Look up an error by pattern match
pub fn lookup_error(pattern: &str) -> Option<(&'static str, &'static str)> {
    let pattern_lower = pattern.to_lowercase();
    KNOWN_ERRORS.iter()
        .find(|(p, _, _)| pattern_lower.contains(&p.to_lowercase()))
        .map(|(_, code, desc)| (*code, *desc))
}
